language: node_js
node_js:
  - 0.11
  - 0.10

addons:
  code_climate:
    repo_token:
      secure: "QXpj5APHhYgEAb+9dbNPSYCI7UfPpCeSmoeRhwPHWuOKqxXK3vKwLeICPvP6JQTaUlPk3xdSQT/8lxb/V7jqXf0nDqdRV6IgPSPoHyV4qPjbHtGh/qOJHi9pCKQTeai0RGuqo2IhF/ONxeiy3QVaSn4k5WrNPmstNGXgzeSFLjQ="

deploy:
  provider: npm
  email: me@samcday.com.au
  api_key:
    secure: N1pXQfcwpMcOexiCDBRXYfQ3WbJP+9RNZZbayb1iNFuhEm50/HxJLdUcV8UInxKkUuS5lSIsWX1KbPKEEtbo6IR5wLTpVUzfYblVmYQI6yoI1XjhcBdYVdlS1uKZUD5ACEfV3Ut112G70XcWks3Drf7/zAuAdvlR3A1mT4E96jQ=
  on:
    tags: true
    all_branches: true
    node_js: 0.10

after_success:
  - "npm run coverage-report"
  - "npm install -g codeclimate-test-reporter"
  - "cat coverage/combined/lcov.info | codeclimate"

env: npm_config_coverage=1 DEBUG=clusterphone:*
